local countries = {
	{
		name = "Afghanistan",
		code = "AF",
		timeZone = "Afghanistan Standard Time",
		utcOffset = "(UTC+04:30)",
		cities = { "Kabul" },
	},
	{
		name = "Åland Islands",
		code = "AX",
		timeZone = "FLE Standard Time",
		utcOffset = "(UTC+02:00)",
		cities = { "Helsinki", "Kyiv", "Riga", "Sofia", "Tallinn", "Vilnius" },
	},
	{
		name = "Albania",
		code = "AL",
		timeZone = "Central Europe Standard Time",
		utcOffset = "(UTC+01:00)",
		cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
	},
	{
		name = "Algeria",
		code = "DZ",
		timeZone = "W. Central Africa Standard Time",
		utcOffset = "(UTC+01:00)",
		cities = { "West Central Africa" },
	},
	{
		name = "American Samoa",
		code = "AS",
		timeZone = "UTC-11",
		utcOffset = "(UTC-11:00)",
		cities = { "Coordinated Universal Time-11" },
	},
	{
		name = "Andorra",
		code = "AD",
		timeZone = "W. Europe Standard Time",
		utcOffset = "(UTC+01:00)",
		cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
	},
	{
		name = "Angola",
		code = "AO",
		timeZone = "W. Central Africa Standard Time",
		utcOffset = "(UTC+01:00)",
		cities = { "West Central Africa" },
	},
	{
		name = "Anguilla",
		code = "AI",
		timeZone = "SA Western Standard Time",
		utcOffset = "(UTC-04:00)",
		cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
	},
	{
		name = "Antarctica",
		code = "AQ",
		timeZone = "Pacific SA Standard Time",
		utcOffset = "(UTC-03:00)",
		cities = { "Santiago" },
	},
	{
		name = "Antigua and Barbuda",
		code = "AG",
		timeZone = "SA Western Standard Time",
		utcOffset = "(UTC-04:00)",
		cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
	},
	{
		name = "Argentina",
		code = "AR",
		timeZone = "Argentina Standard Time",
		utcOffset = "(UTC-03:00)",
		cities = { "City of Buenos Aires" },
	},
	{
		name = "Armenia",
		code = "AM",
		timeZone = "Caucasus Standard Time",
		utcOffset = "(UTC+04:00)",
		cities = { "Yerevan" },
	},
	{
		name = "Aruba",
		code = "AW",
		timeZone = "SA Western Standard Time",
		utcOffset = "(UTC-04:00)",
		cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
	},
	{
		name = "Australia",
		code = "AU",
		timeZone = "AUS Eastern Standard Time",
		utcOffset = "(UTC+10:00)",
		cities = { "Canberra", "Melbourne", "Sydney" },
		{
			name = "Austria",
			code = "AT",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Azerbaijan",
			code = "AZ",
			timeZone = "Azerbaijan Standard Time",
			utcOffset = "(UTC+04:00)",
			cities = { "Baku" },
		},
		{
			name = "Bahamas",
			code = "BS",
			timeZone = "Eastern Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Eastern Time (US & Canada)" },
		},
		{
			name = "Bahrain",
			code = "BH",
			timeZone = "Arabian Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Kuwait", "Riyadh" },
		},
		{
			name = "Bangladesh",
			code = "BD",
			timeZone = "Bangladesh Standard Time",
			utcOffset = "(UTC+06:00)",
			cities = { "Dhaka" },
		},
		{
			name = "Barbados",
			code = "BB",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Belarus",
			code = "BY",
			timeZone = "Belarus Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Minsk" },
		},
		{
			name = "Belgium",
			code = "BE",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Belize",
			code = "BZ",
			timeZone = "Central Standard Time (Mexico)",
			utcOffset = "(UTC-06:00)",
			cities = { "Guadalajara", "Mexico City", "Monterrey" },
		},
		{
			name = "Benin",
			code = "BJ",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Bermuda",
			code = "BM",
			timeZone = "Atlantic Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Atlantic Time (Canada)" },
		},
		{
			name = "Bhutan",
			code = "BT",
			timeZone = "Bangladesh Standard Time",
			utcOffset = "(UTC+06:00)",
			cities = { "Dhaka" },
		},
		{
			name = "Bolivia",
			code = "BO",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Bonaire, Sint Eustatius and Saba",
			code = "BQ",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Bosnia and Herzegovina",
			code = "BA",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Botswana",
			code = "BW",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "Bouvet Island",
			code = "BV",
			timeZone = "UTC+01",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Brazil",
			code = "BR",
			timeZone = "E. South America Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Brasilia" },
		},
		{
			name = "British Indian Ocean Territory",
			code = "IO",
			timeZone = "UTC+06",
			utcOffset = "(UTC+06:00)",
			cities = { "Astana" },
		},
		{
			name = "Brunei Darussalam",
			code = "BN",
			timeZone = "Singapore Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Kuala Lumpur", "Singapore" },
		},
		{
			name = "Bulgaria",
			code = "BG",
			timeZone = "FLE Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Helsinki", "Kyiv", "Riga", "Sofia", "Tallinn", "Vilnius" },
		},
		{
			name = "Burkina Faso",
			code = "BF",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Burundi",
			code = "BI",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "Cambodia",
			code = "KH",
			timeZone = "SE Asia Standard Time",
			utcOffset = "(UTC+07:00)",
			cities = { "Bangkok", "Hanoi", "Jakarta" },
		},
		{
			name = "Cameroon",
			code = "CM",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Canada",
			code = "CA",
			timeZone = "Eastern Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Eastern Time (US & Canada)" },
		},
		{
			name = "Cape Verde",
			code = "CV",
			timeZone = "Cape Verde Standard Time",
			utcOffset = "(UTC-01:00)",
			cities = { "Cape Verde Is." },
		},
		{
			name = "Cayman Islands",
			code = "KY",
			timeZone = "SA Pacific Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Bogota", "Lima", "Quito" },
		},
		{
			name = "Central African Republic",
			code = "CF",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Chad",
			code = "TD",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Chile",
			code = "CL",
			timeZone = "Pacific SA Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Santiago" },
		},
		{
			name = "China",
			code = "CN",
			timeZone = "China Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Beijing", "Chongqing", "Hong Kong", "Urumqi" },
		},
		{
			name = "Christmas Island",
			code = "CX",
			timeZone = "SE Asia Standard Time",
			utcOffset = "(UTC+07:00)",
			cities = { "Bangkok", "Hanoi", "Jakarta" },
		},
		{
			name = "Cocos (Keeling) Islands",
			code = "CC",
			timeZone = "Myanmar Standard Time",
			utcOffset = "(UTC+06:30)",
			cities = { "Yangon (Rangoon)" },
		},
		{
			name = "Colombia",
			code = "CO",
			timeZone = "SA Pacific Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Bogota", "Lima", "Quito" },
		},
		{
			name = "Comoros",
			code = "KM",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Congo",
			code = "CG",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Cook Islands",
			code = "CK",
			timeZone = "Hawaiian Standard Time",
			utcOffset = "(UTC-10:00)",
			cities = { "Hawaii" },
		},
		{
			name = "Costa Rica",
			code = "CR",
			timeZone = "Central Standard Time (Mexico)",
			utcOffset = "(UTC-06:00)",
			cities = { "Guadalajara", "Mexico City", "Monterrey" },
		},
		{
			name = "Côte d'Ivoire",
			code = "CI",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Croatia",
			code = "HR",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Cuba",
			code = "CU",
			timeZone = "SA Pacific Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Bogota", "Lima", "Quito" },
		},
		{
			name = "Curaçao",
			code = "CW",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Cyprus",
			code = "CY",
			timeZone = "GTB Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Athens", "Bucharest" },
		},
		{
			name = "Czech Republic",
			code = "CZ",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Denmark",
			code = "DK",
			timeZone = "Romance Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Brussels", "Copenhagen", "Madrid", "Paris" },
		},
		{
			name = "Djibouti",
			code = "DJ",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Dominica",
			code = "DM",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Dominican Republic",
			code = "DO",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Ecuador",
			code = "EC",
			timeZone = "SA Pacific Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Bogota", "Lima", "Quito" },
		},
		{
			name = "Egypt",
			code = "EG",
			timeZone = "Egypt Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Cairo" },
		},
		{
			name = "El Salvador",
			code = "SV",
			timeZone = "Central Standard Time (Mexico)",
			utcOffset = "(UTC-06:00)",
			cities = { "Guadalajara", "Mexico City", "Monterrey" },
		},
		{
			name = "Equatorial Guinea",
			code = "GQ",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Eritrea",
			code = "ER",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Estonia",
			code = "EE",
			timeZone = "FLE Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Helsinki", "Kyiv", "Riga", "Sofia", "Tallinn", "Vilnius" },
		},
		{
			name = "Eswatini",
			code = "SZ",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "Ethiopia",
			code = "ET",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Falkland Islands (Malvinas)",
			code = "FK",
			timeZone = "SA Eastern Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Buenos Aires" },
		},
		{
			name = "Faroe Islands",
			code = "FO",
			timeZone = "Greenland Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Greenland" },
		},
		{
			name = "Fiji",
			code = "FJ",
			timeZone = "Fiji Standard Time",
			utcOffset = "(UTC+12:00)",
			cities = { "Fiji", "Kamchatka", "Marshall Is." },
		},
		{
			name = "Finland",
			code = "FI",
			timeZone = "FLE Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Helsinki", "Kyiv", "Riga", "Sofia", "Tallinn", "Vilnius" },
		},
		{
			name = "France",
			code = "FR",
			timeZone = "Romance Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Brussels", "Copenhagen", "Madrid", "Paris" },
		},
		{
			name = "French Guiana",
			code = "GF",
			timeZone = "SA Eastern Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Buenos Aires" },
		},
		{
			name = "French Polynesia",
			code = "PF",
			timeZone = "Hawaiian Standard Time",
			utcOffset = "(UTC-10:00)",
			cities = { "Hawaii" },
		},
		{
			name = "French Southern Territories",
			code = "TF",
			timeZone = "UTC+03",
			utcOffset = "(UTC+03:00)",
			cities = { "Moscow", "St. Petersburg", "Volgograd" },
		},
		{
			name = "Gabon",
			code = "GA",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Gambia",
			code = "GM",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Georgia",
			code = "GE",
			timeZone = "Georgian Standard Time",
			utcOffset = "(UTC+04:00)",
			cities = { "Tbilisi" },
		},
		{
			name = "Germany",
			code = "DE",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Ghana",
			code = "GH",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Gibraltar",
			code = "GI",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Greece",
			code = "GR",
			timeZone = "GTB Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Athens", "Bucharest" },
		},
		{
			name = "Greenland",
			code = "GL",
			timeZone = "Greenland Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Greenland" },
		},
		{
			name = "Grenada",
			code = "GD",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Guadeloupe",
			code = "GP",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Guam",
			code = "GU",
			timeZone = "West Pacific Standard Time",
			utcOffset = "(UTC+10:00)",
			cities = { "Guam", "Port Moresby" },
		},
		{
			name = "Guatemala",
			code = "GT",
			timeZone = "Central Standard Time (Mexico)",
			utcOffset = "(UTC-06:00)",
			cities = { "Guadalajara", "Mexico City", "Monterrey" },
		},
		{
			name = "Guernsey",
			code = "GG",
			timeZone = "GMT Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Dublin", "Edinburgh", "Lisbon", "London" },
		},
		{
			name = "Guinea",
			code = "GN",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Guinea-Bissau",
			code = "GW",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Guyana",
			code = "GY",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Haiti",
			code = "HT",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Heard Island and McDonald Islands",
			code = "HM",
			timeZone = "UTC+06",
			utcOffset = "(UTC+06:00)",
			cities = { "Astana" },
		},
		{
			name = "Holy See (Vatican City State)",
			code = "VA",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Honduras",
			code = "HN",
			timeZone = "Central Standard Time (Mexico)",
			utcOffset = "(UTC-06:00)",
			cities = { "Guadalajara", "Mexico City", "Monterrey" },
		},
		{
			name = "Hong Kong",
			code = "HK",
			timeZone = "China Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Beijing", "Chongqing", "Hong Kong", "Urumqi" },
		},
		{
			name = "Hungary",
			code = "HU",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Iceland",
			code = "IS",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "India",
			code = "IN",
			timeZone = "India Standard Time",
			utcOffset = "(UTC+05:30)",
			cities = { "Chennai", "Kolkata", "Mumbai", "New Delhi" },
		},
		{
			name = "Indonesia",
			code = "ID",
			timeZone = "SE Asia Standard Time",
			utcOffset = "(UTC+07:00)",
			cities = { "Bangkok", "Hanoi", "Jakarta" },
		},
		{
			name = "Iran, Islamic Republic of",
			code = "IR",
			timeZone = "Iran Standard Time",
			utcOffset = "(UTC+03:30)",
			cities = { "Tehran" },
		},
		{
			name = "Iraq",
			code = "IQ",
			timeZone = "Arabic Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Kuwait", "Riyadh" },
		},
		{
			name = "Ireland",
			code = "IE",
			timeZone = "GMT Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Dublin", "Edinburgh", "Lisbon", "London" },
		},
		{
			name = "Isle of Man",
			code = "IM",
			timeZone = "GMT Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Dublin", "Edinburgh", "Lisbon", "London" },
		},
		{
			name = "Israel",
			code = "IL",
			timeZone = "Israel Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Jerusalem" },
		},
		{
			name = "Italy",
			code = "IT",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Jamaica",
			code = "JM",
			timeZone = "SA Pacific Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Bogota", "Lima", "Quito" },
		},
		{
			name = "Japan",
			code = "JP",
			timeZone = "Tokyo Standard Time",
			utcOffset = "(UTC+09:00)",
			cities = { "Osaka", "Sapporo", "Tokyo" },
		},
		{
			name = "Jersey",
			code = "JE",
			timeZone = "GMT Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Dublin", "Edinburgh", "Lisbon", "London" },
		},
		{
			name = "Jordan",
			code = "JO",
			timeZone = "Jordan Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Amman" },
		},
		{
			name = "Kazakhstan",
			code = "KZ",
			timeZone = "Central Asia Standard Time",
			utcOffset = "(UTC+06:00)",
			cities = { "Almaty", "Astana", "Novosibirsk" },
		},
		{
			name = "Kenya",
			code = "KE",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Kiribati",
			code = "KI",
			timeZone = "UTC+13",
			utcOffset = "(UTC+13:00)",
			cities = { "Nuku'alofa" },
		},
		{
			name = "Korea, Democratic People's Republic of",
			code = "KP",
			timeZone = "North Korea Standard Time",
			utcOffset = "(UTC+09:00)",
			cities = { "Pyongyang" },
		},
		{
			name = "Korea, Republic of",
			code = "KR",
			timeZone = "Korea Standard Time",
			utcOffset = "(UTC+09:00)",
			cities = { "Seoul" },
		},
		{
			name = "Kuwait",
			code = "KW",
			timeZone = "Arabic Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Kuwait", "Riyadh" },
		},
		{
			name = "Kyrgyzstan",
			code = "KG",
			timeZone = "Central Asia Standard Time",
			utcOffset = "(UTC+06:00)",
			cities = { "Almaty", "Astana", "Novosibirsk" },
		},
		{
			name = "Lao People's Democratic Republic",
			code = "LA",
			timeZone = "SE Asia Standard Time",
			utcOffset = "(UTC+07:00)",
			cities = { "Bangkok", "Hanoi", "Jakarta" },
		},
		{
			name = "Latvia",
			code = "LV",
			timeZone = "FLE Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Helsinki", "Kyiv", "Riga", "Sofia", "Tallinn", "Vilnius" },
		},
		{
			name = "Lebanon",
			code = "LB",
			timeZone = "Middle East Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Beirut" },
		},
		{
			name = "Lesotho",
			code = "LS",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "Liberia",
			code = "LR",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Libyan Arab Jamahiriya",
			code = "LY",
			timeZone = "Libya Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Tripoli" },
		},
		{
			name = "Liechtenstein",
			code = "LI",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Lithuania",
			code = "LT",
			timeZone = "FLE Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Helsinki", "Kyiv", "Riga", "Sofia", "Tallinn", "Vilnius" },
		},
		{
			name = "Luxembourg",
			code = "LU",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Macao",
			code = "MO",
			timeZone = "China Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Beijing", "Chongqing", "Hong Kong", "Urumqi" },
		},
		{
			name = "Macedonia, the former Yugoslav Republic of",
			code = "MK",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Madagascar",
			code = "MG",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Malawi",
			code = "MW",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "Malaysia",
			code = "MY",
			timeZone = "Singapore Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Kuala Lumpur", "Singapore" },
		},
		{
			name = "Maldives",
			code = "MV",
			timeZone = "West Asia Standard Time",
			utcOffset = "(UTC+05:00)",
			cities = { "Islamabad", "Karachi", "Tashkent" },
		},
		{
			name = "Mali",
			code = "ML",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Malta",
			code = "MT",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Marshall Islands",
			code = "MH",
			timeZone = "UTC+12",
			utcOffset = "(UTC+12:00)",
			cities = { "Fiji", "Kamchatka", "Marshall Is." },
		},
		{
			name = "Martinique",
			code = "MQ",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Mauritania",
			code = "MR",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Mauritius",
			code = "MU",
			timeZone = "Mauritius Standard Time",
			utcOffset = "(UTC+04:00)",
			cities = { "Port Louis" },
		},
		{
			name = "Mayotte",
			code = "YT",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Mexico",
			code = "MX",
			timeZone = "Central Standard Time (Mexico)",
			utcOffset = "(UTC-06:00)",
			cities = { "Guadalajara", "Mexico City", "Monterrey" },
		},
		{
			name = "Micronesia, Federated States of",
			code = "FM",
			timeZone = "Central Pacific Standard Time",
			utcOffset = "(UTC+11:00)",
			cities = { "Solomon Is.", "New Caledonia" },
		},
		{
			name = "Moldova, Republic of",
			code = "MD",
			timeZone = "E. Europe Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Chisinau" },
		},
		{
			name = "Monaco",
			code = "MC",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Mongolia",
			code = "MN",
			timeZone = "Ulaanbaatar Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Ulaanbaatar" },
		},
		{
			name = "Montenegro",
			code = "ME",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Montserrat",
			code = "MS",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Morocco",
			code = "MA",
			timeZone = "Morocco Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Casablanca" },
		},
		{
			name = "Mozambique",
			code = "MZ",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "Myanmar",
			code = "MM",
			timeZone = "Myanmar Standard Time",
			utcOffset = "(UTC+06:30)",
			cities = { "Yangon (Rangoon)" },
		},
		{
			name = "Namibia",
			code = "NA",
			timeZone = "Namibia Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Windhoek" },
		},
		{
			name = "Nauru",
			code = "NR",
			timeZone = "UTC+12",
			utcOffset = "(UTC+12:00)",
			cities = { "Fiji", "Kamchatka", "Marshall Is." },
		},
		{
			name = "Nepal",
			code = "NP",
			timeZone = "Nepal Standard Time",
			utcOffset = "(UTC+05:45)",
			cities = { "Kathmandu" },
		},
		{
			name = "Netherlands",
			code = "NL",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "New Caledonia",
			code = "NC",
			timeZone = "Central Pacific Standard Time",
			utcOffset = "(UTC+11:00)",
			cities = { "Solomon Is.", "New Caledonia" },
		},
		{
			name = "New Zealand",
			code = "NZ",
			timeZone = "New Zealand Standard Time",
			utcOffset = "(UTC+12:00)",
			cities = { "Auckland", "Wellington" },
		},
		{
			name = "Nicaragua",
			code = "NI",
			timeZone = "Central Standard Time (Mexico)",
			utcOffset = "(UTC-06:00)",
			cities = { "Guadalajara", "Mexico City", "Monterrey" },
		},
		{
			name = "Niger",
			code = "NE",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Nigeria",
			code = "NG",
			timeZone = "W. Central Africa Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "West Central Africa" },
		},
		{
			name = "Niue",
			code = "NU",
			timeZone = "UTC-11",
			utcOffset = "(UTC-11:00)",
			cities = { "Samoa", "Pago Pago" },
		},
		{
			name = "Norfolk Island",
			code = "NF",
			timeZone = "Norfolk Standard Time",
			utcOffset = "(UTC+11:00)",
			cities = { "Solomon Is.", "New Caledonia" },
		},
		{
			name = "North Macedonia",
			code = "MK",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Northern Mariana Islands",
			code = "MP",
			timeZone = "West Pacific Standard Time",
			utcOffset = "(UTC+10:00)",
			cities = { "Guam", "Port Moresby" },
		},
		{
			name = "Norway",
			code = "NO",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Oman",
			code = "OM",
			timeZone = "Arabian Standard Time",
			utcOffset = "(UTC+04:00)",
			cities = { "Abu Dhabi", "Muscat" },
		},
		{
			name = "Pakistan",
			code = "PK",
			timeZone = "Pakistan Standard Time",
			utcOffset = "(UTC+05:00)",
			cities = { "Islamabad", "Karachi", "Tashkent" },
		},
		{
			name = "Palau",
			code = "PW",
			timeZone = "Tokyo Standard Time",
			utcOffset = "(UTC+09:00)",
			cities = { "Osaka", "Sapporo", "Tokyo" },
		},
		{
			name = "Palestinian Territory, Occupied",
			code = "PS",
			timeZone = "Israel Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Jerusalem" },
		},
		{
			name = "Panama",
			code = "PA",
			timeZone = "SA Pacific Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Bogota", "Lima", "Quito" },
		},
		{
			name = "Papua New Guinea",
			code = "PG",
			timeZone = "West Pacific Standard Time",
			utcOffset = "(UTC+10:00)",
			cities = { "Guam", "Port Moresby" },
		},
		{
			name = "Paraguay",
			code = "PY",
			timeZone = "Paraguay Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Asuncion" },
		},
		{
			name = "Peru",
			code = "PE",
			timeZone = "SA Pacific Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Bogota", "Lima", "Quito" },
		},
		{
			name = "Philippines",
			code = "PH",
			timeZone = "Singapore Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Kuala Lumpur", "Singapore" },
		},
		{
			name = "Pitcairn",
			code = "PN",
			timeZone = "UTC-08",
			utcOffset = "(UTC-08:00)",
			cities = { "Pacific Time (US & Canada)" },
		},
		{
			name = "Poland",
			code = "PL",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Portugal",
			code = "PT",
			timeZone = "GMT Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Dublin", "Edinburgh", "Lisbon", "London" },
		},
		{
			name = "Puerto Rico",
			code = "PR",
			timeZone = "Atlantic Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Caracas", "La Paz" },
		},
		{
			name = "Qatar",
			code = "QA",
			timeZone = "Arabian Standard Time",
			utcOffset = "(UTC+04:00)",
			cities = { "Abu Dhabi", "Muscat" },
		},
		{
			name = "Réunion",
			code = "RE",
			timeZone = "Mauritius Standard Time",
			utcOffset = "(UTC+04:00)",
			cities = { "Port Louis" },
		},
		{
			name = "Romania",
			code = "RO",
			timeZone = "E. Europe Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Athens", "Bucharest" },
		},
		{
			name = "Russian Federation",
			code = "RU",
			timeZone = "Russia Time Zone 3",
			utcOffset = "(UTC+04:00)",
			cities = { "Moscow", "St. Petersburg", "Volgograd" },
		},
		{
			name = "Rwanda",
			code = "RW",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "Saint Helena, Ascension and Tristan da Cunha",
			code = "SH",
			timeZone = "GMT Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Dublin", "Edinburgh", "Lisbon", "London" },
		},
		{
			name = "Saint Kitts and Nevis",
			code = "KN",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Saint Lucia",
			code = "LC",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Saint Pierre and Miquelon",
			code = "PM",
			timeZone = "Greenland Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Greenland" },
		},
		{
			name = "Saint Vincent and the Grenadines",
			code = "VC",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Samoa",
			code = "WS",
			timeZone = "UTC+13",
			utcOffset = "(UTC+13:00)",
			cities = { "Samoa", "Pago Pago" },
		},
		{
			name = "San Marino",
			code = "SM",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Sao Tome and Principe",
			code = "ST",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Saudi Arabia",
			code = "SA",
			timeZone = "Arabian Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Kuwait", "Riyadh" },
		},
		{
			name = "Senegal",
			code = "SN",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Serbia",
			code = "RS",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Seychelles",
			code = "SC",
			timeZone = "Mauritius Standard Time",
			utcOffset = "(UTC+04:00)",
			cities = { "Port Louis" },
		},
		{
			name = "Sierra Leone",
			code = "SL",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Singapore",
			code = "SG",
			timeZone = "Singapore Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Kuala Lumpur", "Singapore" },
		},
		{
			name = "Slovakia",
			code = "SK",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Slovenia",
			code = "SI",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Solomon Islands",
			code = "SB",
			timeZone = "Central Pacific Standard Time",
			utcOffset = "(UTC+11:00)",
			cities = { "Solomon Is.", "New Caledonia" },
		},
		{
			name = "Somalia",
			code = "SO",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "South Africa",
			code = "ZA",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "South Georgia and the South Sandwich Islands",
			code = "GS",
			timeZone = "UTC-02",
			utcOffset = "(UTC-02:00)",
			cities = { "Mid-Atlantic - Old" },
		},
		{
			name = "South Sudan",
			code = "SS",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Spain",
			code = "ES",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Sri Lanka",
			code = "LK",
			timeZone = "Sri Lanka Standard Time",
			utcOffset = "(UTC+05:30)",
			cities = { "Sri Jayawardenepura" },
		},
		{
			name = "Sudan",
			code = "SD",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Suriname",
			code = "SR",
			timeZone = "SA Eastern Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Brasilia" },
		},
		{
			name = "Svalbard and Jan Mayen",
			code = "SJ",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Sweden",
			code = "SE",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Switzerland",
			code = "CH",
			timeZone = "W. Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Amsterdam", "Berlin", "Bern", "Rome", "Stockholm", "Vienna" },
		},
		{
			name = "Syrian Arab Republic",
			code = "SY",
			timeZone = "Syria Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Damascus" },
		},
		{
			name = "Taiwan, Province of China",
			code = "TW",
			timeZone = "China Standard Time",
			utcOffset = "(UTC+08:00)",
			cities = { "Beijing", "Chongqing", "Hong Kong", "Urumqi" },
		},
		{
			name = "Tajikistan",
			code = "TJ",
			timeZone = "West Asia Standard Time",
			utcOffset = "(UTC+05:00)",
			cities = { "Ashgabat", "Tashkent" },
		},
		{
			name = "Tanzania, United Republic of",
			code = "TZ",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Thailand",
			code = "TH",
			timeZone = "SE Asia Standard Time",
			utcOffset = "(UTC+07:00)",
			cities = { "Bangkok", "Hanoi", "Jakarta" },
		},
		{
			name = "Timor-Leste",
			code = "TL",
			timeZone = "Tokyo Standard Time",
			utcOffset = "(UTC+09:00)",
			cities = { "Osaka", "Sapporo", "Tokyo" },
		},
		{
			name = "Togo",
			code = "TG",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Tokelau",
			code = "TK",
			timeZone = "UTC+13",
			utcOffset = "(UTC+13:00)",
			cities = { "Samoa", "Pago Pago" },
		},
		{
			name = "Tonga",
			code = "TO",
			timeZone = "Tonga Standard Time",
			utcOffset = "(UTC+13:00)",
			cities = { "Nuku'alofa" },
		},
		{
			name = "Trinidad and Tobago",
			code = "TT",
			timeZone = "SA Western Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Georgetown", "La Paz", "Manaus", "San Juan" },
		},
		{
			name = "Tunisia",
			code = "TN",
			timeZone = "Central Europe Standard Time",
			utcOffset = "(UTC+01:00)",
			cities = { "Belgrade", "Bratislava", "Budapest", "Ljubljana", "Prague" },
		},
		{
			name = "Turkey",
			code = "TR",
			timeZone = "Turkey Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Istanbul" },
		},
		{
			name = "Turkmenistan",
			code = "TM",
			timeZone = "West Asia Standard Time",
			utcOffset = "(UTC+05:00)",
			cities = { "Ashgabat", "Tashkent" },
		},
		{
			name = "Turks and Caicos Islands",
			code = "TC",
			timeZone = "Eastern Standard Time",
			utcOffset = "(UTC-05:00)",
			cities = { "Bogota", "Lima", "Quito" },
		},
		{
			name = "Tuvalu",
			code = "TV",
			timeZone = "UTC+12",
			utcOffset = "(UTC+12:00)",
			cities = { "Fiji", "Kamchatka", "Marshall Is." },
		},
		{
			name = "Uganda",
			code = "UG",
			timeZone = "E. Africa Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Nairobi" },
		},
		{
			name = "Ukraine",
			code = "UA",
			timeZone = "FLE Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Helsinki", "Kyiv", "Riga", "Sofia", "Tallinn", "Vilnius" },
		},
		{
			name = "United Arab Emirates",
			code = "AE",
			timeZone = "Arabian Standard Time",
			utcOffset = "(UTC+04:00)",
			cities = { "Abu Dhabi", "Muscat" },
		},
		{
			name = "United Kingdom",
			code = "GB",
			timeZone = "GMT Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Dublin", "Edinburgh", "Lisbon", "London" },
		},
		{
			name = "United States",
			code = "US",
			timeZone = "Pacific Standard Time",
			utcOffset = "(UTC-08:00)",
			cities = { "Pacific Time (US & Canada)" },
		},
		{
			name = "United States Minor Outlying Islands",
			code = "UM",
			timeZone = "UTC-11",
			utcOffset = "(UTC-11:00)",
			cities = { "Midway Island", "Samoa" },
		},
		{
			name = "Uruguay",
			code = "UY",
			timeZone = "Montevideo Standard Time",
			utcOffset = "(UTC-03:00)",
			cities = { "Montevideo" },
		},
		{
			name = "Uzbekistan",
			code = "UZ",
			timeZone = "West Asia Standard Time",
			utcOffset = "(UTC+05:00)",
			cities = { "Ashgabat", "Tashkent" },
		},
		{
			name = "Vanuatu",
			code = "VU",
			timeZone = "Central Pacific Standard Time",
			utcOffset = "(UTC+11:00)",
			cities = { "Solomon Is.", "New Caledonia" },
		},
		{
			name = "Venezuela, Bolivarian Republic of",
			code = "VE",
			timeZone = "Venezuela Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Caracas", "La Paz" },
		},
		{
			name = "Viet Nam",
			code = "VN",
			timeZone = "SE Asia Standard Time",
			utcOffset = "(UTC+07:00)",
			cities = { "Bangkok", "Hanoi", "Jakarta" },
		},
		{
			name = "Virgin Islands, British",
			code = "VG",
			timeZone = "Atlantic Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Caracas", "La Paz" },
		},
		{
			name = "Virgin Islands, U.S.",
			code = "VI",
			timeZone = "Atlantic Standard Time",
			utcOffset = "(UTC-04:00)",
			cities = { "Caracas", "La Paz" },
		},
		{
			name = "Wallis and Futuna",
			code = "WF",
			timeZone = "UTC+12",
			utcOffset = "(UTC+12:00)",
			cities = { "Fiji", "Kamchatka", "Marshall Is." },
		},
		{
			name = "Western Sahara",
			code = "EH",
			timeZone = "Greenwich Standard Time",
			utcOffset = "(UTC+00:00)",
			cities = { "Casablanca", "Monrovia" },
		},
		{
			name = "Yemen",
			code = "YE",
			timeZone = "Arabian Standard Time",
			utcOffset = "(UTC+03:00)",
			cities = { "Kuwait", "Riyadh" },
		},
		{
			name = "Zambia",
			code = "ZM",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
		{
			name = "Zimbabwe",
			code = "ZW",
			timeZone = "South Africa Standard Time",
			utcOffset = "(UTC+02:00)",
			cities = { "Harare", "Pretoria" },
		},
	},
}

return countries
